name: CI workflow to run tests and check for formatting

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Formatting
      run: rustfmt ./src/*

    - name: Run tests
      run: cargo test
